-- 제약(PK/UNIQUE)이 자동으로 만드는 인덱스는 제외했다. 01_tables.sql 을 먼저 돌리면 그쪽에서 생긴다.

CREATE INDEX idx_blocks_blocked ON public.blocks USING btree (blocked_id);
CREATE INDEX idx_blocks_blocker ON public.blocks USING btree (blocker_id);
CREATE INDEX guardian_verifications_phone_created_idx ON public.guardian_verifications USING btree (guardian_phone, created_at DESC);
CREATE INDEX heart_message_favorites_user_message_idx ON public.heart_message_favorites USING btree (user_id, message_id);
CREATE INDEX heart_message_hides_user_idx ON public.heart_message_hides USING btree (user_id, message_id);
CREATE INDEX heart_messages_mission_idx ON public.heart_messages USING btree (receiver_id, sender_id, created_at) WHERE (replied_at IS NULL);
CREATE INDEX idx_hm_memory ON public.heart_messages USING btree (memory_id);
CREATE INDEX idx_hm_receiver_created ON public.heart_messages USING btree (receiver_id, created_at DESC);
CREATE INDEX idx_hm_room_created ON public.heart_messages USING btree (room_id, created_at DESC);
CREATE INDEX idx_hm_sender_created ON public.heart_messages USING btree (sender_id, created_at DESC);
CREATE INDEX idx_invitations_inviter ON public.invitations USING btree (inviter_id);
CREATE INDEX idx_invitations_room ON public.invitations USING btree (room_id);
CREATE INDEX idx_invitations_unused ON public.invitations USING btree (room_id) WHERE (used_at IS NULL);
CREATE INDEX idx_invitations_used_by ON public.invitations USING btree (used_by);
CREATE INDEX idx_memories_author ON public.memories USING btree (author_id);
CREATE INDEX idx_memories_room_created ON public.memories USING btree (room_id, created_at DESC);
CREATE UNIQUE INDEX memories_one_pin_per_room_idx ON public.memories USING btree (room_id) WHERE ((pinned_at IS NOT NULL) AND (deleted_at IS NULL));
CREATE INDEX memories_room_pinned_created_idx ON public.memories USING btree (room_id, pinned_at DESC NULLS LAST, created_at DESC) WHERE (deleted_at IS NULL);
CREATE INDEX memory_comments_author_idx ON public.memory_comments USING btree (author_id);
CREATE INDEX memory_comments_memory_idx ON public.memory_comments USING btree (memory_id, created_at) WHERE (deleted_at IS NULL);
CREATE INDEX memory_hides_memory_idx ON public.memory_hides USING btree (memory_id);
CREATE INDEX memory_hides_user_idx ON public.memory_hides USING btree (user_id);
CREATE INDEX memory_likes_memory_idx ON public.memory_likes USING btree (memory_id);
CREATE INDEX memory_likes_user_idx ON public.memory_likes USING btree (user_id);
CREATE INDEX memory_photos_memory_idx ON public.memory_photos USING btree (memory_id, sort_order);
CREATE INDEX memory_saves_memory_idx ON public.memory_saves USING btree (memory_id);
CREATE INDEX memory_saves_user_idx ON public.memory_saves USING btree (user_id);
CREATE INDEX notifications_inbox_idx ON public.notifications USING btree (recipient_id, created_at DESC) WHERE (deleted_at IS NULL);
CREATE UNIQUE INDEX push_subscriptions_token_key ON public.push_subscriptions USING btree (token) WHERE (token IS NOT NULL);
CREATE INDEX push_subscriptions_user_id_idx ON public.push_subscriptions USING btree (user_id);
CREATE INDEX idx_reports_reporter ON public.reports USING btree (reporter_id);
CREATE INDEX idx_reports_status ON public.reports USING btree (status, created_at DESC);
CREATE INDEX idx_room_members_room ON public.room_members USING btree (room_id) WHERE (status = 'active'::member_status);
CREATE INDEX idx_room_members_user ON public.room_members USING btree (user_id) WHERE (status = 'active'::member_status);
CREATE INDEX room_members_user_favorited_idx ON public.room_members USING btree (user_id, favorited) WHERE (status = 'active'::member_status);
CREATE INDEX idx_rooms_owner ON public.rooms USING btree (owner_id);
CREATE UNIQUE INDEX users_username_key ON public.users USING btree (username);
